# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  disko.devices = {
    disk.sda = {
      type = "disk";
      device = "/dev/sda";
      content = {
        type = "table";
        format = "gpt";
        partitions = [
          {
            type = "partition";
            name = "ESP";
            start = "1MiB";
            end = "256MiB";
            bootable = true;
            content = {
              type = "filesystem";
              format = "vfat";
              mountpoint = "/boot";
            };
          }
          {
            type = "partition";
            name = "luks";
            start = "256MiB";
            end = "100%";
            content = {
              type = "luks";
              name = "cryptroot";
              keyFile = ./secrets/cryptroot.key;
              content = {
                type = "lvm_pv";
                vg = "nixos";
              };
            };
          }
        ];
      };
    };

    lvm_vg.nixos = {
      type = "lvm_vg";
      lvs = {
        root = {
          type = "lvm_lv";
          size = "5G";
          content = {
            type = "filesystem";
            format = "ext4";
            mountpoint = "/";
          };
        };
        swap = {
          type = "lvm_lv";
          size = "8G";
          content = {
            type = "swap";
            randomEncryption = true;
          };
        };
        var = {
          type = "lvm_lv";
          size = "30G";
          content = {
            type = "filesystem";
            format = "ext4";
            mountpoint = "/var";
          };
        };
        nix = {
          type = "lvm_lv";
          size = "150G";
          content = {
            type = "filesystem";
            format = "ext4";
            mountpoint = "/nix";
          };
        };
        home = {
          type = "lvm_lv";
          size = "+100%FREE";
          content = {
            type = "filesystem";
            format = "btrfs";
            mountpoint = "/home";
          };
        };
      };
    };
  };

  swapDevices =
    [{ device = "/dev/mapper/nixos-swap"; }];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
