# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "usb_storage" "sdhci_pci" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/c5a1e73d-44b9-4530-9ccc-927e0fa48e0a";
      fsType = "btrfs";
    };

  fileSystems."/var" =
    {
      device = "/dev/disk/by-uuid/20a74805-fd6b-4669-b36c-7cda7d44c3ce";
      fsType = "btrfs";
    };

  fileSystems."/nix" =
    {
      device = "/dev/disk/by-uuid/6e4def11-d4c1-4b83-a3b6-560386d2f8f8";
      fsType = "btrfs";
    };

  fileSystems."/home" =
    {
      device = "/dev/disk/by-uuid/eba7acbf-a6d8-492e-b005-543521a8a8ca";
      fsType = "btrfs";
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/8415-181B";
      fsType = "vfat";
    };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/7f3d7722-b509-4ba5-a3a5-160ed7568e33"; }];

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "ondemand";
}
